services:
  centos7:
    platform: linux/amd64
    build: centos7
    image: centos7-for-btpd

  btp-daemon:
    platform: linux/amd64
    build: btp-daemon
    ports:
      - "37000:37000"
      - "37001:37001"
      - "37002:37002"
      - "37003:37003"
      - "37004:37004"
      - "38001:38001"
      - "38001:38001/udp"
    volumes:
      - ./storage:/storage