FROM centos:7

RUN yum install -y \
  wget \
  gcc-c++ \
  snappy snappy-devel \
  zlib zlib-devel \
  bzip2 bzip2-devel \
  lz4-devel \
  libasan \
  gflags \
  boost-devel \
  make \
  cmake \
  git \
  which

