FROM centos:7

RUN yum install -y \
  wget \
  gcc-c++ \
  snappy snappy-devel \
  zlib zlib-devel \
  bzip2 bzip2-devel \
  lz4-devel \
  libasan \
  gflags \
  boost boost-devel boost-system boost-datetime \
  jemalloc jemalloc-devel \
  libzstd libzstd-devel \
  librt librt-devel \
  make \
  cmake \
  git \
  which

